# zwischentoncloud configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
bind-host = "localhost"
port = 2340

[database]
password = "we4711"

[tls]
zwischenton-root-ca = "/usr/local/zwischentoncloud/ca.crt"
cert = "/usr/local/zwischentoncloud/server.crt"
key = "/usr/local/zwischentoncloud/server.key"

[jwt]
expiration = 180
accesspublickeypath = "/usr/local/zwischentoncloud/authentication.publickey.pem"
accessprivatekeypath = "/usr/local/zwischentoncloud/authentication.privatekey.pem"


[log]
info = "/var/log/zwischentoncloud/info.log"
trace = "/var/log/zwischentoncloud/trace.log"