name: Release Go Binaries

on: 
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:  
          - goarch: arm64
            goos: linux 
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - name: Set BUILD_TIME env
      run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}

    - uses: wangyoucao577/go-release-action@v1.51
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        asset_name: zwischentoncloud-${{ matrix.goos }}-${{ matrix.goarch }}
        build_flags: -v
        ldflags: -X 'github.com/TR-Projekt/ZwischentonCloud/server/status.ServerVersion=${{ env.APP_VERSION }}' -X 'github.com/TR-Projekt/ZwischentonCloud/server/status.BuildTime=${{ env.BUILD_TIME }}' -X 'github.com/TR-Projekt/ZwischentonCloud/server/status.GitRef=${{ github.ref }}'
        extra_files: LICENSE README.md config_template.toml operation/service_template.service operation/update.sh
